extends Node2D

const section_time := 2.0
const line_time := 0.3
const base_speed := 50
const speed_up_multiplier := 10.0
const title_color := Color.BLUE

var scroll_speed := base_speed
var speed_up := false

@onready var line := $CreditsContainer/Line
var started := false
var finished := false

var section
var section_next := true
var section_timer := 0.0
var line_timer := 0.0
var curr_line := 0
var lines := []

var credits = [
	[
		"A game by Greatfruit Games"
	],[
		"Programming",
		"Greatfruit",
	],[
		"Art",
		"Greatfruit",
	],[
		"Music",
		"Greatfruit",
	],[
		"Sound Effects",
		"Generated by Greatfruit using jsfxr by chr15m",
		"https://sfxr.me/",
	],[
		"Tools Used",
		"Developed with Godot Engine",
		"https://godotengine.org/",
		"",
		"Art created with Aseprite",
		"https://www.aseprite.org/",
		"",
		"Music Created in LMMS",
		"https://lmms.io/",
	],[
		"Other Contributions",
		"Credits display script by benbishpnz",
		"https://github.com/benbishopnz/godot-credits",
		"",
		"Original Godot Engine logo by Andrea Calabró",
		"https://github.com/godotengine/godot/blob/master/misc/logo/LICENSE.txt",
		"",
		"Clouds in motion shader by gerardogc2378",
		"https://godotshaders.com/shader/clouds-in-motion/"
	],[
		"Thanks for playing"
	]
]


func _process(delta: float) -> void:
	var scroll_speed = base_speed * delta

	if section_next:
		section_timer += delta * speed_up_multiplier if speed_up else delta
		if section_timer >= section_time:
			section_timer -= section_time

			if credits.size() > 0:
				started = true
				section = credits.pop_front()
				curr_line = 0
				add_line()

	else:
		line_timer += delta * speed_up_multiplier if speed_up else delta
		if line_timer >= line_time:
			line_timer -= line_time
			add_line()

	if speed_up:
		scroll_speed *= speed_up_multiplier

	if lines.size() > 0:
		for l in lines:
			l.position.y -= scroll_speed
			if l.position.y < -l.get_line_height():
				lines.erase(l)
				l.queue_free()
	elif started:
		finish()

func finish():
	if not finished:
		finished = true
		await get_tree().create_timer(1).timeout
		
		await get_tree().create_timer(1).timeout
		get_tree().change_scene_to_file("res://Scenes/title_screen.tscn")

func add_line():
	var new_line = line.duplicate()
	new_line.text = section.pop_front()
	lines.append(new_line)
	$CreditsContainer.add_child(new_line)
	if section.size() > 0:
		curr_line += 1
		section_next = false
	else:
		section_next = false

func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("ui_cancel"):
		finish()
	if event.is_action_pressed("ui_down") and !event.is_echo():
		speed_up = true
	if event.is_action_released("ui_down") and !event.is_echo():
		speed_up = false